### ISSUE TITLE
OutOfRangeError: PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements

### ISSUE THREAD

**Issue by SuX97** [Kongsea/FPN_TensorFlow#1]
Hi, I have followed your steps to convert my own tfrecord and start to train, yet there is something wrong called "OutOfRangeError: PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements".

Do you know what might be the cause of this error?

Thanks!

**Comment by Kongsea** [comment]
I think it was caused by the inconsistency of the tfrecord data and the data reader.
Please check it first.

**Comment by niuniu111** [comment]
Have you tried the effect of the VGg network?

**Comment by Kongsea** [comment]
I have not tried it.
Maybe you can have a try.

**Comment by niuniu111** [comment]
I made a mistake when I tried, showing this mistake：ValueError: Shape of a new variable (vgg_16/fc8/weights) must be fully defined, but instead was (1, 1, 4096, ?)，I think it's my training model and I don't know where to download it.

**Comment by Kongsea** [comment]
How about defining the inputs fully?
Such as:
`inputs = tf.placeholder(tf.float32, [FLAGS.batch_size, 224, 224, 3], name='inputs')`

**Comment by TVXQ20031226** [comment]
> I made a mistake when I tried, showing this mistake：ValueError: Shape of a new variable (vgg_16/fc8/weights) must be fully defined, but instead was (1, 1, 4096, ?)，I think it's my training model and I don't know where to download it.

have you solved this problem？？I met this issue too！！hope your reply~~

**Comment by TVXQ20031226** [comment]
> I made a mistake when I tried, showing this mistake：ValueError: Shape of a new variable (vgg_16/fc8/weights) must be fully defined, but instead was (1, 1, 4096, ?)，I think it's my training model and I don't know where to download it.

have you solved this problem?? I met this issue too!!  thanks in advance~~@niuniu111
