### ISSUE TITLE
你好，看精度直接运行eval.py吗？ 

### ISSUE THREAD

**Issue by niuniu111** [Kongsea/FPN_TensorFlow#10]

**Comment by Kongsea** [comment]
是的。

**Comment by niuniu111** [comment]
我有个疑问，运行时的Num是测试图片数目还是训练图片数目，还是所有图片数，图像路径是不是和num对应，评价网络时的输出路径又是什么，我还是有疑问，能否帮我解释一下，谢谢

**Comment by niuniu111** [comment]
测试了我的模型，精度只有26%，但是检测结果挺好的，感觉冲突，不知道怎么解释这种现象，希望能够交流一下，你能解释一下吗？谢谢

**Comment by JoanHHH** [comment]
@niuniu111 你好，请问如何运行eval.py呢？需要处理什么图片吗？直接run就行吗？还有img_num又是什么的数目呢？

**Comment by Kongsea** [comment]
@niuniu111 @JoanHHH 关于各参数的意义，麻烦稍微进入代码看一下吧。我现在已经很久没有用这个了，所以也记不清楚了。

@niuniu111 另外，关于精度的问题，我也不好解释。不过如果追求精度的话，推荐使用Detectron吧。那个更好一些，而且是官方的，我现在一直在用那个了。
