### ISSUE TITLE
生成classes.txt出现问题

### ISSUE THREAD

**Issue by xiaoluenbi** [Kongsea/FPN_TensorFlow#14]
我想使用pascal voc2007数据集进行训练，数据集本身有Anonotions，tfrecords文件，那么我该怎样生成classes.txt文件呢

**Comment by Kongsea** [comment]
运行根目录下的gen_classes.py

**Comment by xiaoluenbi** [comment]
>           运行根目录下的gen_classes.py

您好，我按照您说的方法运行了根目录下的gen_classes.py文件，在data目录下生成了一个.txt文件，但是里面是空的，并没有内容。

**Comment by Kongsea** [comment]
检查一下标注和图片路径看看。应该是没有按照要求对应好，或者按要求改一下；或者根据自己的文件修改一下代码。
