### ISSUE TITLE
checkpoint_path error!

### ISSUE THREAD

**Issue by lfdeep** [Kongsea/FPN_TensorFlow#5]
Hello! I run eval.sh ,it occured:
Traceback (most recent call last):
  File "./tools/eval.py", line 326, in <module>
    eval_dict_convert(args)
  File "./tools/eval.py", line 109, in eval_dict_convert
    restorer, restore_ckpt = restore_model.get_restorer(checkpoint_path=args.weights)
TypeError: get_restorer() got an unexpected keyword argument 'checkpoint_path'

**Comment by Kongsea** [comment]
The function `restore_model.get_restorer` has an argument called 'checkpoint_path' actually, as [this](https://github.com/Kongsea/FPN_TensorFlow/blob/master/tools/restore_model.py#L17).
So this error seems very unreasonable.
