### ISSUE TITLE
which datasets to use

### ISSUE THREAD

**Issue by zuowanghanguang** [Kongsea/FPN_TensorFlow#6]
Hello:
 I just want to know what datasets you use in this project.I can't find any datasets about one target to train.Do I need to crate my own datasets?
Thank you!

**Comment by Kongsea** [comment]
Your own custom dataset or the public `coco` or `pascal voc` can both be used to train the network.

**Comment by zuowanghanguang** [comment]
@Kongsea OK.Thank you!
